#pragma once

#include "doomdef.hpp"

enum INPUTS : int
{
    NOTHING = 0,
    MOVE_FORWARD = KEY_UPARROW,
    MOVE_BACKWARD = KEY_DOWNARROW,
    MOVE_LEFT = KEY_LEFTARROW,
    MOVE_RIGHT = KEY_RIGHTARROW,
    MOVE_SPRINT = KEY_RSHIFT,
    W = 'w',
    A = 'a',
    S = 's',
    D = 'd',
    MENU = KEY_ESCAPE,
    RETURN = KEY_ENTER,
    TAB = KEY_TAB,
    F1 = KEY_F1,
    F2 = KEY_F2,
    F3 = KEY_F3,
    F4 = KEY_F4,
    F5 = KEY_F5,
    F6 = KEY_F6,
    F7 = KEY_F7,
    F8 = KEY_F8,
    F9 = KEY_F9,
    F10 = KEY_F10,
    F11 = KEY_F11,
    F12 = KEY_F12,
    BACKSPACE = KEY_BACKSPACE,
    PAUSE = KEY_PAUSE,
    EQUALS = KEY_EQUALS,
    MINUS = KEY_MINUS,
    SHIFT = KEY_RSHIFT,
    CTRL = KEY_RCTRL,
    ALT = KEY_RALT,
    KP_0 = '0',
    KP_1 = '1',
    KP_2 = '2',
    KP_3 = '3',
    KP_4 = '4',
    KP_5 = '5',
    KP_6 = '6',
    KP_7 = '7',
    KP_8 = '8',
    KP_9 = '9',
    MOUSE_LEFT = 256,
    MOUSE_MIDDLE,
    MOUSE_RIGHT,
    ATTACK,
    USE,
    NEXT_WEAPON,
    WEAPON_1,
    WEAPON_2,
    WEAPON_3,
    WEAPON_4,
    WEAPON_5,
    WEAPON_6,
    WEAPON_7,
    WEAPON_8
};
